### ISSUE TITLE
[ERROR] Error invoking callback

### ISSUE THREAD

**Issue by csportalsk** [oscar-wos/Refiller#4]
Linux:
Metamod:Source version 2.0.0-dev+1314
Current API Version: v286 (1.0.286+1f904a5)
[#3:LOADED]: "Refiller" (1.0.1) by github.com/oscar-wos/Refiller

```
2024-11-08 16:54:15.425 +01:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Refiller.Refiller.<>c__DisplayClass12_0.<OnPlayerDeath>b__0() in /home/runner/work/Refiller/Refiller/src/Refiller.cs:line 46
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by oscar-wos** [comment]
thanks for issue https://github.com/oscar-wos/Refiller/commit/d96c6efb24b68316a67f543b25c3bbb862d793c5
